# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(121210)
$foreground = rgb(E3E4E4)
$color0 = rgb(3A3A39)
$color1 = rgb(414132)
$color2 = rgb(665149)
$color3 = rgb(717679)
$color4 = rgb(CA8A10)
$color5 = rgb(AAA5A9)
$color6 = rgb(AFB1B2)
$color7 = rgb(CFCFD0)
$color8 = rgb(919192)
$color9 = rgb(414132)
$color10 = rgb(665149)
$color11 = rgb(717679)
$color12 = rgb(CA8A10)
$color13 = rgb(AAA5A9)
$color14 = rgb(AFB1B2)
$color15 = rgb(CFCFD0)
