# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(101012)
$foreground = rgb(F7E7E9)
$color0 = rgb(39393A)
$color1 = rgb(7D5B6D)
$color2 = rgb(636987)
$color3 = rgb(8A83B3)
$color4 = rgb(B699B0)
$color5 = rgb(D9B0B1)
$color6 = rgb(E7BAC0)
$color7 = rgb(EBD4D7)
$color8 = rgb(A49497)
$color9 = rgb(7D5B6D)
$color10 = rgb(636987)
$color11 = rgb(8A83B3)
$color12 = rgb(B699B0)
$color13 = rgb(D9B0B1)
$color14 = rgb(E7BAC0)
$color15 = rgb(EBD4D7)
