# Wallust generated btop theme
# Based on Adapta Template

# Main background, empty for terminal default
theme[main_bg]=""

# Main text color
theme[main_fg]="#E3E4E4"

# Title color for boxes
theme[title]="#CFCFD0"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#414132"

# Background color of selected item in processes box
theme[selected_bg]="#414132"

# Foreground color of selected item in processes box
theme[selected_fg]="#E3E4E4"

# Color of inactive/disabled text
theme[inactive_fg]="#919192"

# Misc colors for processes box
theme[proc_misc]="#AAA5A9"

# Box outline colors
theme[cpu_box]="#CA8A10"
theme[mem_box]="#CA8A10"
theme[net_box]="#CA8A10"
theme[proc_box]="#CA8A10"

# Box divider line and small boxes line color
theme[div_line]="#919192"

# Temperature graph colors
theme[temp_start]="#CA8A10"
theme[temp_mid]="#717679"
theme[temp_end]="#414132"

# CPU graph colors
theme[cpu_start]="#CA8A10"
theme[cpu_mid]="#717679"
theme[cpu_end]="#414132"

# Mem/Disk free meter
theme[free_start]="#665149"
theme[free_mid]="#665149"
theme[free_end]="#AFB1B2"

# Mem/Disk cached meter
theme[cached_start]="#AAA5A9"
theme[cached_mid]="#AAA5A9"
theme[cached_end]="#AAA5A9"

# Mem/Disk available meter
theme[available_start]="#AFB1B2"
theme[available_mid]="#AFB1B2"
theme[available_end]="#AFB1B2"

# Mem/Disk used meter
theme[used_start]="#414132"
theme[used_mid]="#414132"
theme[used_end]="#414132"

# Download graph colors
theme[download_start]="#665149"
theme[download_mid]="#AFB1B2"
theme[download_end]="#CA8A10"

# Upload graph colors
theme[upload_start]="#414132"
theme[upload_mid]="#AAA5A9"
theme[upload_end]="#AAA5A9"
