# Main background, empty for terminal default
theme[main_bg]=""

# Main text color
theme[main_fg]="{{foreground}}"

# Title color for boxes
theme[title]="{{color15}}"

# Highlight color for keyboard shortcuts
theme[hi_fg]="{{color1}}"

# Background color of selected item in processes box
theme[selected_bg]="{{color1}}"

# Foreground color of selected item in processes box
theme[selected_fg]="{{foreground}}"

# Color of inactive/disabled text
theme[inactive_fg]="{{color8}}"

# Misc colors for processes box
theme[proc_misc]="{{color13}}"

# Box outline colors
theme[cpu_box]="{{color4}}"
theme[mem_box]="{{color4}}"
theme[net_box]="{{color4}}"
theme[proc_box]="{{color4}}"

# Box divider line and small boxes line color
theme[div_line]="{{color8}}"

# Temperature graph colors
theme[temp_start]="{{color4}}"
theme[temp_mid]="{{color3}}"
theme[temp_end]="{{color1}}"

# CPU graph colors
theme[cpu_start]="{{color4}}"
theme[cpu_mid]="{{color3}}"
theme[cpu_end]="{{color1}}"

# Mem/Disk free meter
theme[free_start]="{{color2}}"
theme[free_mid]="{{color10}}"
theme[free_end]="{{color14}}"

# Mem/Disk cached meter
theme[cached_start]="{{color5}}"
theme[cached_mid]="{{color13}}"
theme[cached_end]="{{color5}}"

# Mem/Disk available meter
theme[available_start]="{{color6}}"
theme[available_mid]="{{color14}}"
theme[available_end]="{{color6}}"

# Mem/Disk used meter
theme[used_start]="{{color1}}"
theme[used_mid]="{{color9}}"
theme[used_end]="{{color1}}"

# Download graph colors
theme[download_start]="{{color2}}"
theme[download_mid]="{{color6}}"
theme[download_end]="{{color4}}"

# Upload graph colors
theme[upload_start]="{{color1}}"
theme[upload_mid]="{{color5}}"
theme[upload_end]="{{color13}}"
