### Sourcing external config files ###
$configs = $HOME/.config/hypr/configs # Configs directory path

# Default apps
source= $configs/DefaultsApps.conf

# Key shortcut
source=$configs/Keybinds.conf # Pre-configured keybinds

# App at startup
source= $configs/StartupApps.conf 

# Environment variables
source= $configs/ENVariables.conf

# Laptop specifica keybinds
source= $configs/Laptops.conf 

# Windowriles
source= $configs/WindowRules.conf

# General settings and decorations
source= $configs/SystemSettings.conf 

# nwg-displays
source= $configs/monitors.conf
