# Wallust generated btop theme
# Based on Adapta Template

# Main background, empty for terminal default
theme[main_bg]=""

# Main text color
theme[main_fg]="#F7E7E9"

# Title color for boxes
theme[title]="#EBD4D7"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#7D5B6D"

# Background color of selected item in processes box
theme[selected_bg]="#7D5B6D"

# Foreground color of selected item in processes box
theme[selected_fg]="#F7E7E9"

# Color of inactive/disabled text
theme[inactive_fg]="#A49497"

# Misc colors for processes box
theme[proc_misc]="#D9B0B1"

# Box outline colors
theme[cpu_box]="#B699B0"
theme[mem_box]="#B699B0"
theme[net_box]="#B699B0"
theme[proc_box]="#B699B0"

# Box divider line and small boxes line color
theme[div_line]="#A49497"

# Temperature graph colors
theme[temp_start]="#B699B0"
theme[temp_mid]="#8A83B3"
theme[temp_end]="#7D5B6D"

# CPU graph colors
theme[cpu_start]="#B699B0"
theme[cpu_mid]="#8A83B3"
theme[cpu_end]="#7D5B6D"

# Mem/Disk free meter
theme[free_start]="#636987"
theme[free_mid]="#636987"
theme[free_end]="#E7BAC0"

# Mem/Disk cached meter
theme[cached_start]="#D9B0B1"
theme[cached_mid]="#D9B0B1"
theme[cached_end]="#D9B0B1"

# Mem/Disk available meter
theme[available_start]="#E7BAC0"
theme[available_mid]="#E7BAC0"
theme[available_end]="#E7BAC0"

# Mem/Disk used meter
theme[used_start]="#7D5B6D"
theme[used_mid]="#7D5B6D"
theme[used_end]="#7D5B6D"

# Download graph colors
theme[download_start]="#636987"
theme[download_mid]="#E7BAC0"
theme[download_end]="#B699B0"

# Upload graph colors
theme[upload_start]="#7D5B6D"
theme[upload_mid]="#D9B0B1"
theme[upload_end]="#D9B0B1"
