$scriptsDir = $HOME/.config/hypr/scripts

binde = , xf86MonBrightnessDown, exec, $scriptsDir/Brightness.sh --dec # decrease monitor brightness
binde = , xf86MonBrightnessUp, exec, $scriptsDir/Brightness.sh --inc # increase monitor brightness

$Touchpad_Device=etps/2-elantech-touchpad

device {
  name = $Touchpad_Device
  enabled = true
}

