$scriptsDir = $HOME/.config/hypr/scripts

binde = , xf86MonBrightnessDown, exec, $scriptsDir/Brightness.sh --dec # decrease monitor brightness
binde = , xf86MonBrightnessUp, exec, $scriptsDir/Brightness.sh --inc # increase monitor brightness

device {
  name = etps/2-elantech-touchpad
  enabled = true
}

