$scriptsDir = $HOME/.config/hypr/script

### Wallpaper daemon ###
exec-once = awww-daemon --format xrgb

### Startup ###
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = $scriptsDir/Polkit.sh
exec-once = nm-applet --indicator
exec-once = swaync
exec-once = kitty
exec-once = waybar
exec-once = hypridle

# Clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Bluethoot
exec-once = blueman-applet  #broken
